version: '3.8'

x-spark-reusable: &spark-reusable
  image: bitnami/spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: Worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
  networks:
    - recommender-node

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    volumes:
      - ./db/neo4j/data:/data
      - ./db/neo4j/conf:/conf
      - ./db/neo4j/logs:/logs
      - ./db/neo4j/plugins:/plugins
    networks:
      - recommender-node

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - recommender-node

  spark-worker-1:
    <<: *spark-reusable
  spark-worker-2:
    <<: *spark-reusable

  fastapi:
    build: ./api
    container_name: fastapi
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    volumes:
      - ./api:/app
    env_file:
      - .env
    networks:
      - recommender-node

networks:
  recommender-node: