version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    volumes:
      - ./db/neo4j/data:/data
      - ./db/neo4j/conf:/conf
      - ./db/neo4j/logs:/logs
      - ./db/neo4j/plugins:/plugins
    networks:
      - recommender-node

  fastapi:
    build: ./api
    container_name: fastapi
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    volumes:
      - ./api:/app
    env_file:
      - .env
    networks:
      - recommender-node

networks:
  recommender-node: